### ISSUE TITLE
text highlighting for scss

### ISSUE THREAD

**Issue by sambedingfield** [pandao/brackets-vue#1]
Thanks for the awesome extension.

How about text highlight support for scss? For example;
```scss
<style lang="scss" scoped>
  $white: #ffffff;
  #menu {
    color: $white;
  }
</style>
```
Will not correctly highlight scss vars and mixins.
